# Just for local development
version: '3.2'
services:
  operator:
    container_name: enonic-k8s-operador-dev
    build:
      context: .
      args:
        VERSION_TAG: dev
    image: 'enonic-k8s-operador-dev'
    environment:
      DEBUG: 1
    network_mode: host
    volumes:
      - ~/.kube/config:/root/.kube/config
      - ./src:/src