---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: enonic-op-dev-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: enonic-op-dev-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [""]
    resources: ["pods"]
    verbs: [list, watch, patch, create, delete, update]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: [list, watch, patch, create, delete, update]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: enonic-op-dev-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enonic-op-dev-role-cluster
subjects:
  - kind: ServiceAccount
    name: enonic-op-dev-account
    namespace: default
---