version: 2.1
executors:
  docker:
    environment:
      SIDECAR_IMAGE: daviptrs/enonic-operator-k8s-sidecar
      OPERATOR_IMAGE: daviptrs/enonic-operator-k8s
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  sidecar-build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - sidecar-{{ .Branch }}
      - run:
          name: Build Docker image
          command: |
            docker build ./sidecar-tool -f ./sidecar-tool/Dockerfile -t $SIDECAR_IMAGE:latest
      - run:
          name: Archive Docker image
          command: docker save -o sidecar.tar $SIDECAR_IMAGE
      - save_cache:
          key: sidecar-{{ .Branch }}-{{ epoch }}
          paths:
            - ./sidecar.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./sidecar.tar
  sidecar-push:
    executor: docker
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/sidecar.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker tag $SIDECAR_IMAGE:latest $SIDECAR_IMAGE:alpha
            docker push $SIDECAR_IMAGE:alpha
            docker push $SIDECAR_IMAGE:latest
  operator-build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - operator-{{ .Branch }}
      - run:
          name: Build Docker image
          command: |
            docker build . -t $OPERATOR_IMAGE:latest
      - run:
          name: Archive Docker image
          command: docker save -o operator.tar $OPERATOR_IMAGE
      - save_cache:
          key: operator-{{ .Branch }}-{{ epoch }}
          paths:
            - ./operator.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./operator.tar
  operator-push:
    executor: docker
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/operator.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker tag $OPERATOR_IMAGE:latest $OPERATOR_IMAGE:alpha
            docker push $OPERATOR_IMAGE:alpha
            docker push $OPERATOR_IMAGE:latest
workflows:
  version: 2
  sidecar-pipeline:
    jobs:
      - sidecar-build:
          filters:
            tags:
              only: /^sidecar-v.*/
            branches:
              ignore: /.*/
      - sidecar-push:
          requires:
            - sidecar-build
          filters:
            tags:
              only: /^sidecar-v.*/
            branches:
              ignore: /.*/
  operator-pipeline:
    jobs:
      - operator-build:
          filters:
            tags:
              only: /^operator-v.*/
            branches:
              ignore: /.*/
      - operator-push:
          requires:
            - operator-build
          filters:
            tags:
              only: /^operator-v.*/
            branches:
              ignore: /.*/