version: 2.1
executors:
  docker:
    environment:
      SIDECAR_IMAGE: daviptrs/enonic-operator-k8s-sidecar
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  sidecar-build:
    executor: docker
    steps:
      - checkout
      - run:
          name: Check if sidecar source code was changed
          command: |
            echo 'git diff --quiet HEAD~ sidecar-tool' >> script.sh
            echo 'if [ $? == 0 ]; then' >> script.sh
            echo 'exit 1' >> script.sh
            echo 'fi' >> script.sh
            chmod +x script.sh
            ./script.sh
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Build Docker image
          command: |
            docker build ./sidecar-tool -f ./sidecar-tool/Dockerfile -t $SIDECAR_IMAGE:latest
      - run:
          name: Archive Docker image
          command: docker save -o sidecar.tar $SIDECAR_IMAGE
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ./sidecar.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./sidecar.tar
  sidecar-push:
    executor: docker
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/sidecar.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker tag $SIDECAR_IMAGE:latest $SIDECAR_IMAGE:alpha
            docker push $SIDECAR_IMAGE:alpha
            docker push $SIDECAR_IMAGE:latest
workflows:
  version: 2
  build-main:
    jobs:
      - sidecar-build:
          filters:
            branches:
              only: main
      - sidecar-push:
          requires:
            - sidecar-build
          filters:
            branches:
              only: main