---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: enonic-operator-account

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: enonic-op-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: ["", "events.k8s.io"]
    resources: [events]
    verbs: [create]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: [get, list, watch, create, delete]

  - apiGroups: ["kopf.enonic"]
    resources: ["enonicxpapps"]
    verbs: [get, list, watch, patch, update]

  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: [get, list, watch, patch, create, delete, update]

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: [get, list, watch, patch]

  - apiGroups: ["apps"]
    resources: ["statefulsets/status"]
    verbs: [get, list, watch, patch]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: enonic-op-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enonic-op-role-cluster
subjects:
  - kind: ServiceAccount
    name: enonic-operator-account
    namespace: default

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: enonicxpapps.kopf.enonic
spec:
  scope: Namespaced
  group: kopf.enonic
  names:
    kind: EnonicXpApp
    plural: enonicxpapps
    singular: enonicxpapp
    shortNames:
      - xpapp
      - xpapps
      - exas
      - exa
      - xapp
      - xapps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Latest Jar
          type: string
          jsonPath: .spec.object.name
          description: Latest jar file that was tried to be installed.
        - name: Bucket path
          type: string
          jsonPath: .spec.bucket.url_sufix
          description: Bucket folder where the jar will be downloaded from.
        - name: Bucket URL
          type: string
          jsonPath: .spec.bucket.url
          description: Bucket URL where the jar will be downloaded from.
        - name: Status
          type: string
          jsonPath: .status.xp_app_handler
          description: Jar latest installation status

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enonic-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: enonic-operator
  template:
    metadata:
      labels:
        application: enonic-operator
    spec:
      serviceAccountName: enonic-operator-account
      containers:
      - name: operator
        image: daviptrs/enonic-operator-k8s:latest
        imagePullPolicy: Always
        env:
          - name: DEBUG
            value: '0'
          - name: QUIET
            value: '0'
