---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: enonic-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: enonic-operator-clusterrole
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: access for management cluster-wide.
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: [get, list, watch, patch]
  - apiGroups: ["apps"]
    resources: ["statefulsets/status"]
    verbs: [get, list, watch, patch]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: enonic-operator-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enonic-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: enonic-operator-account
    namespace: default
---