apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: enonicxpapps.kopf.enonic
spec:
  scope: Namespaced
  group: kopf.enonic
  names:
    kind: EnonicXpApp
    plural: enonicxpapps
    singular: enonicxpapp
    shortNames:
      - xpapp
      - xpapps
      - exas
      - exa
      - xapp
      - xapps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true