apiVersion: apps/v1
kind: Deployment
metadata:
  name: enonic-op-dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: enonic-op-dev
  template:
    metadata:
      labels:
        application: enonic-op-dev
    spec:
      serviceAccountName: enonic-op-dev-account
      containers:
      - name: operator
        image: daviptrs/enonic-operator-k8s:dev
        imagePullPolicy: Always
        env:
          - name: DEBUG
            value: '1'
          - name: QUIET
            value: '0'