---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: enonic-op-dev-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: enonic-op-dev-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: ["", "events.k8s.io"]
    resources: [events]
    verbs: [create]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: [get, list, watch, create, delete]

  - apiGroups: ["kopf.enonic"]
    resources: ["enonicxpapps"]
    verbs: [get, list, watch, patch, update]

  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: [get, list, watch, patch, create, delete, update]

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: [get, list, watch, patch]

  - apiGroups: ["apps"]
    resources: ["statefulsets/status"]
    verbs: [get, list, watch, patch]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: enonic-op-dev-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enonic-op-dev-role-cluster
subjects:
  - kind: ServiceAccount
    name: enonic-op-dev-account
    namespace: default
---